# Generated by Django 5.0.7 on 2024-07-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pr_photo',
            field=models.ImageField(upload_to='pr_img'),
        ),
    ]
