# Generated by Django 5.0.7 on 2024-07-29 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_category_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
    ]
